package cn.ac.lai.dao;

import java.sql.*;

public class DBConnect{	
	private Connection conn = null; 
	private PreparedStatement pstmt = null; 
	
	public DBConnect() {
		
	}
	
	private void closeDB() {
		if (conn != null) {
			try {
				this.conn.close(); 
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
		
		if (this.pstmt != null) {
			try {
				this.pstmt.close(); 
			} catch (Exception e) {
				e.printStackTrace(); 
			}
		}
		
		System.out.println("DB - closed!"); 
	}
	
	public void openDB() {
		try {
			Class.forName("com.mysql.jdbc.Driver");
		} catch (ClassNotFoundException e) {
			e.printStackTrace(); 
		}
		
		try {
			this.conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/chemicalDemo", "root", "123456");
		} catch (Exception e) {
			e.printStackTrace();  
		}
		
		System.out.println("DB - connected!"); 
	}
	
	public PreparedStatement getPreparedStatement(String sql, int autoGeneratedKeys) {
		try {
			this.pstmt = this.conn.prepareStatement(sql, autoGeneratedKeys); 
		} catch (SQLException e) {
			System.out.println(e.getMessage()); 
		}
		
		return this.pstmt; 
	}
	
	public PreparedStatement getPreparedStatement(String sql) {
		try {
			this.pstmt = this.conn.prepareStatement(sql); 
		} catch (SQLException e) {
			System.out.println(e.getMessage()); 
		}
		
		return this.pstmt; 
	}
	
	public void closePSTMT() {
		closeDB(); 
	}
}